import ('SimpleLUI', 'SimpleLUI.API.Core')
import ('SimpleLUI', 'SimpleLUI.API.Core.Math')
-- Auto Generated by SLUI 'Unity's UI to Lua Converter'
-- Time 04.08.2019 03:03:02

-- objects
local panel1 = core:Create('Panel1')
local panel2 = core:Create('Panel2')
local panel3 = core:Create('Panel3')
local button = core:Create('Button')
local text = core:Create('Text')

-- parents
panel2.rectTransform:SetParent(panel1.rectTransform)
panel3.rectTransform:SetParent(panel2.rectTransform)
button.rectTransform:SetParent(panel3.rectTransform)
text.rectTransform:SetParent(button.rectTransform)

-- anchors
panel1.rectTransform:SetAnchor('Stretch')
panel2.rectTransform:SetAnchor('Stretch')
panel3.rectTransform:SetAnchor('StretchBottom')
button.rectTransform:SetAnchor('BottomRight')
text.rectTransform:SetAnchor('Stretch')

-- transforms

-- Panel1
panel1.rectTransform.pivot = SLUIVector2(0.5, 0.5)
panel1.rectTransform.anchoredPosition = SLUIVector2(0, 0)
panel1.rectTransform.sizeDelta = SLUIVector2(-132, -132)
panel1.rectTransform.localRotation = SLUIQuaternion(0, 0.3151064, 0, 0.9490564)
panel1.rectTransform.localScale = SLUIVector2(1, 1)

-- Panel2
panel2.rectTransform.pivot = SLUIVector2(0.5, 0.5)
panel2.rectTransform.anchoredPosition = SLUIVector2(0, 0)
panel2.rectTransform.sizeDelta = SLUIVector2(-30, -30)
panel2.rectTransform.localRotation = SLUIQuaternion(0, 0, 0, 1)
panel2.rectTransform.localScale = SLUIVector2(1, 1)

-- Panel3
panel3.rectTransform.pivot = SLUIVector2(0.5, 0.5)
panel3.rectTransform.anchoredPosition = SLUIVector2(0, 41.7)
panel3.rectTransform.sizeDelta = SLUIVector2(0, 83.5)
panel3.rectTransform.localRotation = SLUIQuaternion(0, 0, 0, 1)
panel3.rectTransform.localScale = SLUIVector2(1, 1)

-- Button
button.rectTransform.pivot = SLUIVector2(0.5, 0.5)
button.rectTransform.anchoredPosition = SLUIVector2(-80.00003, 41.5)
button.rectTransform.sizeDelta = SLUIVector2(160, 84)
button.rectTransform.localRotation = SLUIQuaternion(0, 0, 0, 1)
button.rectTransform.localScale = SLUIVector2(1, 1)

-- Text
text.rectTransform.pivot = SLUIVector2(0.5, 0.5)
text.rectTransform.anchoredPosition = SLUIVector2(0, 0)
text.rectTransform.sizeDelta = SLUIVector2(-30, -30)
text.rectTransform.localRotation = SLUIQuaternion(0, 0, 0, 1)
text.rectTransform.localScale = SLUIVector2(1, 1)

-- images

-- Panel1
local panel1_image = panel1:AddComponent('Image')
panel1_image:SetType('Sliced')
panel1_image.color = SLUIColor(1, 1, 1, 0.392)
panel1_image.sprite = 'LUI//auto_res//Background.png'

-- Panel2
local panel2_image = panel2:AddComponent('Image')
panel2_image:SetType('Sliced')
panel2_image.color = SLUIColor(1, 1, 1, 0.392)
panel2_image.sprite = 'LUI//auto_res//Background.png'

-- Panel3
local panel3_image = panel3:AddComponent('Image')
panel3_image:SetType('Sliced')
panel3_image.color = SLUIColor(1, 1, 1, 1)
panel3_image.sprite = 'LUI//auto_res//Background.png'

-- Button
local button_image = button:AddComponent('Image')
button_image:SetType('Sliced')
button_image.color = SLUIColor(1, 1, 1, 1)
button_image.sprite = 'LUI//auto_res//UISprite.png'
